name: JSON eval

# The event that triggers the action.
on: 
  push: 
    branches: 
      - main
    paths: 
      - 'ontology-network/musical-performance/**'
  workflow_dispatch:
 
jobs:

  verify-json-validation:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Validate JSON
          uses: docker://orrosenblatt/validate-json-action:latest
          env:
            INPUT_JSONS: .xd-testing/Musical Performance/Recording Session/expectedResults/ER01.json
      
